from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Compra_itens(Base):
    __tablename__ = 'compra_itens'
    id = Column(INTEGER, primary_key=True)
    fk_compra = Column(INTEGER)
    empresa = Column(SMALLINT)
    item = Column(SMALLINT)
    fk_produto = Column(INTEGER)
    cfop = Column(VARCHAR)
    cst_icm = Column(VARCHAR)
    vl_unitario = Column(DECIMAL)
    qtd = Column(DECIMAL)
    e_medio = Column(DECIMAL)
    vl_item = Column(DECIMAL)
    base_ipi = Column(DECIMAL)
    aliq_ipi = Column(DECIMAL)
    vl_ipi = Column(DECIMAL)
    base_icms = Column(DECIMAL)
    aliq_icms = Column(DECIMAL)
    vl_icms = Column(DECIMAL)
    base_st = Column(DECIMAL)
    vl_st = Column(DECIMAL)
    base_pis = Column(DECIMAL)
    aliq_pis = Column(DECIMAL)
    vl_pis = Column(DECIMAL)
    base_cof = Column(DECIMAL)
    aliq_cof = Column(DECIMAL)
    vl_cof = Column(DECIMAL)
    frete1 = Column(DECIMAL)
    despesa = Column(DECIMAL)
    seguro = Column(DECIMAL)
    desconto = Column(DECIMAL)
    gera_cp = Column(VARCHAR)
    gera_es = Column(VARCHAR)
    situacao = Column(VARCHAR)
    fk_produto_forn = Column(VARCHAR)
    cst_pis = Column(VARCHAR)
    cst_cof = Column(VARCHAR)
    cst_ipi = Column(VARCHAR)
    aliq_st = Column(DECIMAL)
    fk_usuario = Column(INTEGER)
    qtd_devolvida = Column(DECIMAL)
    total = Column(BIGINT)
    pr_venda = Column(DECIMAL)
