from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from funcoes import db

class Config(db.Model):
    __tablename__ = 'config'
    versao = Column(INTEGER, primary_key=True)
    data_script = Column(DATE)
    estilo = Column(VARCHAR)
    link_treinamento = Column(VARCHAR)
    titulo_sistema = Column(VARCHAR)
    sub_titulo_sistema = Column(VARCHAR)
    email_suporte = Column(VARCHAR)
    site = Column(VARCHAR)
    fone1 = Column(VARCHAR)
    fone2 = Column(VARCHAR)
    contato = Column(VARCHAR)
    empresa = Column(VARCHAR)
    ftp_servidor = Column(VARCHAR)
    ftp_usuario = Column(VARCHAR)
    ftp_senha = Column(VARCHAR)
    ftp_pasta = Column(VARCHAR)
    ftp_arquivo = Column(VARCHAR)
    usuario_li = Column(VARCHAR)
    tela_abertura = Column(VARCHAR)
    tela_fundo = Column(VARCHAR)
    tela_fundo_ecf = Column(VARCHAR)
    menu_maximizado = Column(VARCHAR)
    senha_li = Column(VARCHAR)
    servidor_app = Column(VARCHAR)
    usuario_app = Column(VARCHAR)
    senha_app = Column(VARCHAR)
    database_app = Column(VARCHAR)
    database_li = Column(VARCHAR)
    icone = Column(BLOB)
    splash = Column(BLOB)
    caminho_logo_fpg = Column(VARCHAR)
    link_venda = Column(VARCHAR)
    mensagem_promocao = Column(VARCHAR)
    enviar_mensagem_aniversario = Column(SMALLINT)
    enviar_mensagem_promocao = Column(SMALLINT)
    enviar_mensagem_diario = Column(SMALLINT)
    mensagem_diario = Column(VARCHAR)
    dia_mensagem_diaria = Column(SMALLINT)
    time_mensagem_diaria = Column(TIME)
    ultimo_envio_promocao = Column(TIMESTAMP)
    mensagem_aniversario = Column(VARCHAR)
    ultimo_envio_aniversario = Column(TIMESTAMP)
    ultimo_envio_diario = Column(TIMESTAMP)
