from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from funcoes import db

class Creceber(db.Model):
    __tablename__ = 'creceber'
    codigo = Column(INTEGER, primary_key=True)
    data = Column(DATE)
    fkcliente = Column(INTEGER)
    doc = Column(VARCHAR)
    valor = Column(DECIMAL)
    dtvencimento = Column(DATE)
    historico = Column(VARCHAR)
    data_recebimento = Column(DATE)
    desconto = Column(DECIMAL)
    juros = Column(DECIMAL)
    vrecebido = Column(DECIMAL)
    vl_restante = Column(DECIMAL)
    situacao = Column(VARCHAR)
    fkempresa = Column(INTEGER)
    fk_venda = Column(INTEGER)
    fkconta = Column(INTEGER)
    tipo = Column(VARCHAR)
    nboleto = Column(INTEGER)
    id_vendedor = Column(INTEGER)
    flag = Column(VARCHAR)
    fk_os = Column(INTEGER)
    fpg_venda = Column(INTEGER)
    cartao = Column(VARCHAR)
    bloqueado = Column(VARCHAR)
    fk_usuario = Column(INTEGER)
    pagamento_loja = Column(CHAR)
    cancelamento_loja = Column(CHAR)
    alteracao_loja = Column(CHAR)
    cancelamento_data = Column(TIMESTAMP)
    remessa = Column(CHAR)
    remessa_reenviar = Column(CHAR)
    remessa_data = Column(DATE)
    remessa_arquivo = Column(VARCHAR)
    registro_id_cbr_retorno = Column(BIGINT)
    registro_status = Column(CHAR)
    registro_data = Column(TIMESTAMP)
    registro_arquivo = Column(VARCHAR)
    retorno_id_cbr_retorno = Column(INTEGER)
    registro_historico = Column(VARCHAR)
    registro_sem_registro = Column(CHAR)
    registro_limite_prazo = Column(CHAR)
    retorno_historico = Column(VARCHAR)
    obs = Column(VARCHAR)
    id_cbr_remessa_uuid = Column(VARCHAR)
    retorno_sem_registro = Column(CHAR)
    retorno_limite_prazo = Column(CHAR)
