from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Cte_master(Base):
    __tablename__ = 'cte_master'
    codigo = Column(INTEGER, primary_key=True)
    fkempresa = Column(INTEGER)
    numero = Column(INTEGER)
    chave = Column(VARCHAR)
    cfop = Column(INTEGER)
    modelo = Column(INTEGER)
    serie = Column(INTEGER)
    codmunenvio = Column(INTEGER)
    municipioenvio = Column(VARCHAR)
    ufenvio = Column(VARCHAR)
    tiposervico = Column(INTEGER)
    codmunini = Column(INTEGER)
    municipioini = Column(VARCHAR)
    ufini = Column(VARCHAR)
    codmunfim = Column(INTEGER)
    minicipiofim = Column(VARCHAR)
    uffim = Column(VARCHAR)
    total = Column(DECIMAL)
    recebido = Column(DECIMAL)
    vpis = Column(DECIMAL)
    vcofins = Column(DECIMAL)
    vinss = Column(DECIMAL)
    vir = Column(DECIMAL)
    vclss = Column(DECIMAL)
    vtottirb = Column(DECIMAL)
    descricaoservico = Column(VARCHAR)
    qtd = Column(DECIMAL)
    respseg = Column(INTEGER)
    xseg = Column(VARCHAR)
    napolice = Column(VARCHAR)
    taf = Column(VARCHAR)
    nroregestadual = Column(VARCHAR)
    tipo = Column(VARCHAR)
    situacao = Column(VARCHAR)
    fktomador = Column(INTEGER)
    fktransportador = Column(INTEGER)
    protocolo = Column(VARCHAR)
    xml = Column(BLOB)
    data = Column(DATE)
    hora = Column(TIME)
    finalidade = Column(INTEGER)
    documento = Column(VARCHAR)
    data_entrega = Column(DATE)
    tomador = Column(VARCHAR)
    fk_destinatario = Column(INTEGER)
    fk_veiculo = Column(VARCHAR)
    obs_fisco = Column(BLOB)
    obs_contribuinte = Column(BLOB)
    valor_servico = Column(DECIMAL)
    valor_carga = Column(DECIMAL)
    cst_icms = Column(VARCHAR)
    aliquota_icms = Column(DECIMAL)
    base_icms = Column(DECIMAL)
    valor_icms = Column(DECIMAL)
    outros_tributos = Column(DECIMAL)
    pesol = Column(DECIMAL)
    pesob = Column(DECIMAL)
    metragem = Column(VARCHAR)
    fk_remetente = Column(INTEGER)
    chave_referenciada = Column(VARCHAR)
    naverbacao = Column(VARCHAR)
    cnpj_seguradora = Column(VARCHAR)
