from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Grupo_tributario(Base):
    __tablename__ = 'grupo_tributario'
    codigo = Column(INTEGER, primary_key=True)
    nome_grupo = Column(VARCHAR)
    origem = Column(INTEGER)
    csosn_consf_f_c_ie = Column(VARCHAR)
    csosn_consf_f_s_ie = Column(VARCHAR)
    csosn_consf_j_c_ie = Column(VARCHAR)
    csosn_consf_j_s_ie = Column(VARCHAR)
    cfop_consf_saida_d_uf = Column(VARCHAR)
    cfop_consf_saida_f_uf = Column(VARCHAR)
    mod_bc_consf_dst_icms_n = Column(INTEGER)
    aliq_icms_d_uf_consf_dst_icms_n = Column(DECIMAL)
    red_bc_d_uf_consf_dst_icms_n = Column(DECIMAL)
    aliq_icms_f_uf_consf_dst_icms_n = Column(DECIMAL)
    red_bc_f_uf_consf_dst_icms_n = Column(DECIMAL)
    fcp_consf_dst_icms_n = Column(DECIMAL)
    ipi_saidas_consf = Column(VARCHAR)
    aliq_ipi_consf = Column(DECIMAL)
    cod_enq_ipi_consf = Column(VARCHAR)
    ipi_entradas_consf = Column(VARCHAR)
    pis_saidas_consf = Column(VARCHAR)
    aliq_pis_consf = Column(DECIMAL)
    pis_entradas_consf = Column(VARCHAR)
    cofins_saidas_consf = Column(VARCHAR)
    aliq_cofins_consf = Column(DECIMAL)
    cofins_entradas_consf = Column(VARCHAR)
    csosn_rev_f_c_ie = Column(VARCHAR)
    csosn_rev_f_s_ie = Column(VARCHAR)
    csosn_rev_j_c_ie = Column(VARCHAR)
    csosn_rev_j_s_ie = Column(VARCHAR)
    cfop_rev_saida_d_uf = Column(VARCHAR)
    cfop_rev_saida_f_uf = Column(VARCHAR)
    mod_bc_rev_dst_icms_n = Column(INTEGER)
    aliq_icms_d_uf_rev_dst_icms_n = Column(DECIMAL)
    red_bc_d_uf_rev_dst_icms_n = Column(DECIMAL)
    aliq_icms_f_uf_rev_dst_icms_n = Column(DECIMAL)
    red_bc_f_uf_rev_dst_icms_n = Column(DECIMAL)
    fcp_rev_dst_icms_n = Column(DECIMAL)
    ipi_saidas_rev = Column(VARCHAR)
    aliq_ipi_revenda = Column(DECIMAL)
    cod_enq_ipi_revenda = Column(VARCHAR)
    ipi_entradas_revenda = Column(VARCHAR)
    pis_saidas_revenda = Column(VARCHAR)
    aliq_pis_revenda = Column(DECIMAL)
    pis_entradas_revenda = Column(VARCHAR)
    cofins_saidas_revenda = Column(VARCHAR)
    aliq_cofins_revenda = Column(DECIMAL)
    cofins_entradas_revenda = Column(VARCHAR)
    csosn_ra_cd_f_c_ie = Column(VARCHAR)
    csosn_ra_cd_f_s_ie = Column(VARCHAR)
    csosn_ra_cd_j_c_ie = Column(VARCHAR)
    csosn_ra_cd_j_s_ie = Column(VARCHAR)
    cfop_ra_cd_saida_d_uf = Column(VARCHAR)
    cfop_ra_cd_saida_f_uf = Column(VARCHAR)
    mod_bc_ra_cd_dst_icms_n = Column(INTEGER)
    aliq_icms_d_uf_ra_cd_dst_icms_n = Column(DECIMAL)
    red_bc_d_uf_ra_cd_dst_icms_n = Column(DECIMAL)
    aliq_icms_f_uf_ra_cd_dst_icms_n = Column(DECIMAL)
    red_bc_f_uf_ra_cd_dst_icms_n = Column(DECIMAL)
    fcp_ra_cd_dst_icms_n = Column(DECIMAL)
    ipi_saidas_revaprov_cred = Column(VARCHAR)
    aliq_ipi_revaprov_cred = Column(DECIMAL)
    cod_enq_ipi_revaprov_cred = Column(VARCHAR)
    ipi_entradas_revaprov_cred = Column(VARCHAR)
    pis_saidas_revaprov_cred = Column(VARCHAR)
    aliq_pis_revaprov_cred = Column(DECIMAL)
    pis_entradas_revaprov_cred = Column(VARCHAR)
    cofins_saidas_revaprov_cred = Column(VARCHAR)
    aliq_cofins_revaprov_cred = Column(DECIMAL)
    cofins_entradas_revaprov_cred = Column(VARCHAR)
