from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Nfe_detalhe(Base):
    __tablename__ = 'nfe_detalhe'
    codigo = Column(INTEGER, primary_key=True)
    fknfe = Column(INTEGER)
    id_produto = Column(INTEGER)
    item = Column(SMALLINT)
    cod_barra = Column(VARCHAR)
    ncm = Column(VARCHAR)
    cfop = Column(VARCHAR)
    cst = Column(VARCHAR)
    csosn = Column(VARCHAR)
    tipo = Column(VARCHAR)
    qtd = Column(DECIMAL)
    e_medio = Column(DECIMAL)
    base_icms = Column(DECIMAL)
    aliq_icms = Column(DECIMAL)
    valor_icms = Column(DECIMAL)
    cst_cofins = Column(VARCHAR)
    base_cofins_icms = Column(DECIMAL)
    aliq_cofins_icms = Column(DECIMAL)
    valor_cofins_icms = Column(DECIMAL)
    cst_pis = Column(VARCHAR)
    base_pis_icms = Column(DECIMAL)
    aliq_pis_icms = Column(DECIMAL)
    valor_pis_icms = Column(DECIMAL)
    trib_mun = Column(DECIMAL)
    trib_est = Column(DECIMAL)
    trib_fed = Column(DECIMAL)
    trib_imp = Column(DECIMAL)
    situacao = Column(VARCHAR)
    flag = Column(VARCHAR)
    unidade = Column(VARCHAR)
    frete = Column(DECIMAL)
    despesas = Column(DECIMAL)
    seguro = Column(DECIMAL)
    desconto = Column(DECIMAL)
    base_ipi = Column(DECIMAL)
    aliq_ipi = Column(DECIMAL)
    valor_ipi = Column(DECIMAL)
    base_icms_st = Column(DECIMAL)
    valor_icms_st = Column(DECIMAL)
    vbcufdest = Column(DECIMAL)
    vfcp = Column(DECIMAL)
    picmsufdest = Column(DECIMAL)
    picmsinter = Column(DECIMAL)
    picmsinterpart = Column(DECIMAL)
    vfcpufdest = Column(DECIMAL)
    vicmsufdest = Column(DECIMAL)
    vicmsufremet = Column(DECIMAL)
    cst_ipi = Column(VARCHAR)
    outros = Column(DECIMAL)
    aliq_icms_st = Column(DECIMAL)
    cest = Column(VARCHAR)
    preco = Column(DECIMAL)
    total = Column(DECIMAL)
    npedido = Column(INTEGER)
    base_desoneracao = Column(DECIMAL)
    aliq_desoneracao = Column(DECIMAL)
    motdesicms = Column(SMALLINT)
    vicmsdeson = Column(DECIMAL)
    info_adicionais = Column(VARCHAR)
    gera_es = Column(VARCHAR)
    evenda = Column(VARCHAR)
    lote = Column(VARCHAR)
    vbcfcpst = Column(DECIMAL)
    pfcpst = Column(DECIMAL)
    vfcpst = Column(DECIMAL)
    vicmsmonoret = Column(DECIMAL)
    qbcmomoret = Column(DECIMAL)
