from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from funcoes import db

class Pessoa(db.Model):
    __tablename__ = 'pessoa'
    empresa = Column(SMALLINT)
    codigo = Column(INTEGER, primary_key=True)
    tipo = Column(VARCHAR)
    cnpj = Column(VARCHAR)
    ie = Column(VARCHAR)
    fantasia = Column(VARCHAR)
    razao = Column(VARCHAR)
    endereco = Column(VARCHAR)
    numero = Column(VARCHAR)
    complemento = Column(VARCHAR)
    codmun = Column(INTEGER)
    municipio = Column(VARCHAR)
    bairro = Column(VARCHAR)
    uf = Column(VARCHAR)
    cep = Column(VARCHAR)
    fone1 = Column(VARCHAR)
    fone2 = Column(VARCHAR)
    celular1 = Column(VARCHAR)
    celular2 = Column(VARCHAR)
    email1 = Column(VARCHAR)
    email2 = Column(VARCHAR)
    foto = Column(BLOB)
    sexo = Column(VARCHAR)
    dt_nasc = Column(DATE)
    ecivil = Column(VARCHAR)
    limite = Column(DECIMAL)
    dia_pgto = Column(SMALLINT)
    obs = Column(BLOB)
    num_usu = Column(SMALLINT)
    fatura = Column(VARCHAR)
    cheque = Column(VARCHAR)
    ccf = Column(VARCHAR)
    spc = Column(VARCHAR)
    isento = Column(VARCHAR)
    forn = Column(VARCHAR)
    fun = Column(VARCHAR)
    cli = Column(VARCHAR)
    fab = Column(VARCHAR)
    tran = Column(VARCHAR)
    adm = Column(VARCHAR)
    ativo = Column(VARCHAR)
    dt_admissao = Column(DATE)
    dt_demissao = Column(DATE)
    salario = Column(DECIMAL)
    pai = Column(VARCHAR)
    mae = Column(VARCHAR)
    banco = Column(VARCHAR)
    agencia = Column(VARCHAR)
    gerente = Column(VARCHAR)
    fone_gerente = Column(VARCHAR)
    propriedade = Column(VARCHAR)
    dt_cadastro = Column(DATE)
    tecnico = Column(VARCHAR)
    atendente = Column(VARCHAR)
    codigo_web = Column(INTEGER)
    tipoproduto = Column(SMALLINT)
    referencia = Column(INTEGER)
    n_venderprazo = Column(VARCHAR)
    ano_envio_mensagem_aniversario = Column(SMALLINT)
