from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from funcoes import db

class Sped_c100(db.Model):
    __tablename__ = 'sped_c100'
    codigo = Column(INTEGER, primary_key=True)
    ind_oper = Column(VARCHAR)
    ind_emit = Column(VARCHAR)
    cod_mod = Column(VARCHAR)
    cod_sit = Column(VARCHAR)
    ser = Column(VARCHAR)
    num_doc = Column(INTEGER)
    chv_nfe = Column(VARCHAR)
    dt_doc = Column(DATE)
    dt_e_s = Column(DATE)
    vl_doc = Column(NUMERIC)
    ind_pgto = Column(VARCHAR)
    vl_desc = Column(NUMERIC)
    vl_abat_nt = Column(NUMERIC)
    vl_merc = Column(NUMERIC)
    ind_frt = Column(NUMERIC)
    vl_seguro = Column(NUMERIC)
    vl_out_da = Column(NUMERIC)
    vl_bc_icms = Column(NUMERIC)
    vl_icms = Column(NUMERIC)
    vl_bc_icms_st = Column(NUMERIC)
    vl_icms_st = Column(NUMERIC)
    vl_ipi = Column(NUMERIC)
    vl_pis = Column(NUMERIC)
    vl_cofins = Column(NUMERIC)
    vl_pis_st = Column(NUMERIC)
    vl_cofins_st = Column(NUMERIC)
    vl_frete = Column(NUMERIC)
    fk_participantes = Column(INTEGER)
    fk_sped = Column(INTEGER)
    fk_empresa = Column(INTEGER)
    fk_usuario = Column(INTEGER)
    tabela = Column(VARCHAR)
    tabela_codigo = Column(INTEGER)
