from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from funcoes import db

class Vendas_master(db.Model):
    __tablename__ = 'vendas_master'
    codigo = Column(INTEGER, primary_key=True)
    data_emissao = Column(DATE)
    data_saida = Column(DATE)
    id_cliente = Column(INTEGER)
    fk_usuario = Column(INTEGER)
    fk_caixa = Column(INTEGER)
    fk_vendedor = Column(INTEGER)
    cpf_nota = Column(VARCHAR)
    subtotal = Column(DECIMAL)
    tipo_desconto = Column(VARCHAR)
    desconto = Column(DECIMAL)
    troco = Column(DECIMAL)
    dinheiro = Column(DECIMAL)
    total = Column(DECIMAL)
    observacoes = Column(BLOB)
    situacao = Column(VARCHAR)
    fkempresa = Column(INTEGER)
    percentual = Column(DECIMAL)
    tipo = Column(VARCHAR)
    necf = Column(INTEGER)
    fkorcamento = Column(INTEGER)
    lote = Column(INTEGER)
    gera_financeiro = Column(VARCHAR)
    percentual_acrescimo = Column(DECIMAL)
    acrescimo = Column(DECIMAL)
    fk_tabela = Column(INTEGER)
    pedido = Column(VARCHAR)
    os = Column(VARCHAR)
    fk_os = Column(INTEGER)
    total_troca = Column(DECIMAL)
    statusentrega = Column(VARCHAR)
    datahorasaida = Column(TIMESTAMP)
    flag_nfce = Column(VARCHAR)
    fk_entregador = Column(INTEGER)
    forma_pagamento = Column(VARCHAR)
    baixouestoque = Column(VARCHAR)
