from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Vendas_terminais(Base):
    __tablename__ = 'vendas_terminais'
    ip = Column(VARCHAR)
    nome = Column(VARCHAR, primary_key=True)
    imprime = Column(VARCHAR)
    usagaveta = Column(VARCHAR)
    fabimpressora = Column(VARCHAR)
    modelo = Column(VARCHAR)
    porta = Column(VARCHAR)
    contingencia = Column(VARCHAR)
    nvias = Column(SMALLINT)
    tipoimpressora = Column(VARCHAR)
    serie = Column(VARCHAR)
    numeracao_inicial = Column(INTEGER)
    empresa = Column(INTEGER)
    velocidade = Column(INTEGER)
    imprime_fechamento = Column(VARCHAR)
    logado = Column(VARCHAR)
    eh_caixa = Column(VARCHAR)
    versao = Column(SMALLINT)
    tipo_browser = Column(VARCHAR)
    balanca_porta = Column(VARCHAR)
    balanca_velocidade = Column(VARCHAR)
    balanca_marca = Column(VARCHAR)
    balanca_paridade = Column(VARCHAR)
    balanca_databits = Column(VARCHAR)
    balanca_stopbits = Column(VARCHAR)
    balanca_handshaking = Column(VARCHAR)
    flag = Column(VARCHAR)
    esc_pos_direto = Column(VARCHAR)
    pagina_codigo = Column(VARCHAR)
    dt_versao = Column(VARCHAR)
    destino_impressao = Column(VARCHAR)
    data_versao = Column(TIMESTAMP)
    tamanho_fonte = Column(INTEGER)
    dt_ultima_atualizacao = Column(TIMESTAMP)
    margem_direita = Column(DECIMAL)
    margem_esquerda = Column(DECIMAL)
    margem_inferior = Column(DECIMAL)
    margem_superior = Column(DECIMAL)
    largura_bobina = Column(INTEGER)
    imprime_duas_linhas = Column(VARCHAR)
    espaco_entre_linhas = Column(VARCHAR)
    linhas_entre_cupom = Column(VARCHAR)
    data_sistema = Column(DATE)
    data_script = Column(TIMESTAMP)
    gerenciador = Column(SMALLINT)
    arquivo_log = Column(VARCHAR)
    impressao_via_cliente = Column(SMALLINT)
    acao_trans_pendente = Column(SMALLINT)
    acao_trans_pendente_inicial = Column(SMALLINT)
    auto_atendimento = Column(SMALLINT)
    imprimir_via_reduzida = Column(SMALLINT)
    confirmar_automaticamente = Column(SMALLINT)
    suporta_desconto = Column(SMALLINT)
    suporta_saque = Column(SMALLINT)
    venda_numero = Column(INTEGER)
    impressora_tef = Column(INTEGER)
    pagina_codigo_tef = Column(INTEGER)
    porta_impressora_tef = Column(VARCHAR)
    colunas_tef = Column(INTEGER)
    linhas_entre_tef = Column(INTEGER)
    espaco_entre_linhas_tef = Column(INTEGER)
    usa_tef = Column(INTEGER)
