from sqlalchemy import Column, INTEGER, DOUBLE, CHAR,TIMESTAMP, VARCHAR, BLOB, NUMERIC, SMALLINT, DATE, DECIMAL, BIGINT, TIME  # Adicione mais tipos conforme necessário
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from funcoes import db

class Xml_detail(db.Model):
    __tablename__ = 'xml_detail'
    codigo = Column(INTEGER, primary_key=True)
    fk_xml_master = Column(INTEGER)
    fk_grupo = Column(INTEGER)
    id_produto_loc = Column(INTEGER)
    id_produto_for = Column(VARCHAR)
    descricao_fornecedor = Column(VARCHAR)
    descricao_local = Column(VARCHAR)
    quant_e = Column(DECIMAL)
    und_e = Column(VARCHAR)
    und_s = Column(VARCHAR)
    preco_e = Column(DECIMAL)
    preco_s = Column(DECIMAL)
    quant_s = Column(DECIMAL)
    vl_item = Column(DECIMAL)
    ncm = Column(VARCHAR)
    cfop = Column(VARCHAR)
    codbarra = Column(VARCHAR)
    cst_ipi = Column(VARCHAR)
    base_ipi = Column(DECIMAL)
    aliq_ipi = Column(DECIMAL)
    vl_ipi = Column(DECIMAL)
    cst_pis = Column(VARCHAR)
    base_pis = Column(DECIMAL)
    aliq_pis = Column(DECIMAL)
    vl_pis = Column(DECIMAL)
    cst_cofins = Column(VARCHAR)
    base_cofins = Column(DECIMAL)
    aliq_cofins = Column(DECIMAL)
    vl_cofins = Column(DECIMAL)
    cst_icms = Column(VARCHAR)
    base_icms = Column(DECIMAL)
    aliq_icms = Column(DECIMAL)
    vl_icms = Column(DECIMAL)
    base_st = Column(DECIMAL)
    aliq_st = Column(DECIMAL)
    vl_st = Column(DECIMAL)
    seguro = Column(DECIMAL)
    despesas = Column(DECIMAL)
    frete = Column(DECIMAL)
    desconto = Column(DECIMAL)
    redbc = Column(DECIMAL)
    fkempresa = Column(INTEGER)
    qtd_total = Column(DECIMAL)
    embalagem = Column(DECIMAL)
    checar = Column(VARCHAR)
    referencia = Column(VARCHAR)
    cfop_e = Column(VARCHAR)
    cst_e = Column(VARCHAR)
    pr_venda = Column(DECIMAL)
    cest = Column(VARCHAR)
