HOSTMYSQL="177.153.69.3"
USERMYSQL="dinheiro"
PASSMYSQL="MT49T3.6%B"
BASEMYSQL="maxservices"

# Substitua com suas próprias credenciais
APP_KEY_DROP_BOX = ''
APP_SECRET_DROP_BOX = ''
ACCESS_TOKEN_DROP_BOX = ''
REFRESH_TOKEN_DROP_BOX = ''
CODIGO_ACESSO_DROP_BOX = ''

SERVIDOR = False
BANCO_SQLITE = ''
PASTA_MAXSUPORT = ''

TOKEN_ZAP = ''
LAST_IMAGE = ''