SET TERM ^ ;

create or alter procedure INSERIR_PRODUTOS_ESTOQUE
as
declare variable COD_EMPRESA integer;
declare variable COD_PRODUTO integer;
declare variable EXISTE integer;
BEGIN
  FOR SELECT CODIGO FROM EMPRESA INTO :COD_EMPRESA DO
  BEGIN
    FOR SELECT CODIGO FROM PRODUTO WHERE EMPRESA = :COD_EMPRESA INTO :COD_PRODUTO DO
    BEGIN
      SELECT COUNT(*) 
      FROM PRODUTO_ESTOQUE 
      WHERE PRODUTO = :COD_PRODUTO AND EMPRESA = :COD_EMPRESA
      INTO :EXISTE;
      
      IF (EXISTE = 0) THEN
      BEGIN
        INSERT INTO PRODUTO_ESTOQUE (PRODUTO, EMPRESA, ESTOQUE_ATUAL)
        VALUES (:COD_PRODUTO, :COD_EMPRESA, 0);
      END
    END
  END
END^

SET TERM ; ^

/* Following GRANT statements are generated automatically */

GRANT SELECT ON EMPRESA TO PROCEDURE INSERIR_PRODUTOS_ESTOQUE;
GRANT SELECT ON PRODUTO TO PROCEDURE INSERIR_PRODUTOS_ESTOQUE;
GRANT SELECT,INSERT ON PRODUTO_ESTOQUE TO PROCEDURE INSERIR_PRODUTOS_ESTOQUE;

/* Existing privileges on this procedure */

GRANT EXECUTE ON PROCEDURE INSERIR_PRODUTOS_ESTOQUE TO MAXSERVICES;
GRANT EXECUTE ON PROCEDURE INSERIR_PRODUTOS_ESTOQUE TO MAXSUPORT;